package com.azimiao.crud.dao;

import com.azimiao.crud.bean.information;
import com.azimiao.crud.bean.informationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface informationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    long countByExample(informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int deleteByExample(informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int insert(information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int insertSelective(information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    List<information> selectByExample(informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    information selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") information record, @Param("example") informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByExample(@Param("record") information record, @Param("example") informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByPrimaryKeySelective(information record);
    
    int updateByUUIDSelective(information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByPrimaryKey(information record);
}