package com.azimiao.crud.dao;

import com.azimiao.crud.bean.product;
import com.azimiao.crud.bean.productExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface productMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    long countByExample(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int deleteByExample(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int deleteByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int insert(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int insertSelective(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    List<product> selectByExample(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    product selectByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") product record, @Param("example") productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByExample(@Param("record") product record, @Param("example") productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByPrimaryKeySelective(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_product
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    int updateByPrimaryKey(product record);
}