package com.azimiao.crud.bean;

import java.util.ArrayList;
import java.util.List;

public class informationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public informationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andLinIsNull() {
            addCriterion("lin is null");
            return (Criteria) this;
        }

        public Criteria andLinIsNotNull() {
            addCriterion("lin is not null");
            return (Criteria) this;
        }

        public Criteria andLinEqualTo(String value) {
            addCriterion("lin =", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinNotEqualTo(String value) {
            addCriterion("lin <>", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinGreaterThan(String value) {
            addCriterion("lin >", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinGreaterThanOrEqualTo(String value) {
            addCriterion("lin >=", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinLessThan(String value) {
            addCriterion("lin <", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinLessThanOrEqualTo(String value) {
            addCriterion("lin <=", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinLike(String value) {
            addCriterion("lin like", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinNotLike(String value) {
            addCriterion("lin not like", value, "lin");
            return (Criteria) this;
        }

        public Criteria andLinIn(List<String> values) {
            addCriterion("lin in", values, "lin");
            return (Criteria) this;
        }

        public Criteria andLinNotIn(List<String> values) {
            addCriterion("lin not in", values, "lin");
            return (Criteria) this;
        }

        public Criteria andLinBetween(String value1, String value2) {
            addCriterion("lin between", value1, value2, "lin");
            return (Criteria) this;
        }

        public Criteria andLinNotBetween(String value1, String value2) {
            addCriterion("lin not between", value1, value2, "lin");
            return (Criteria) this;
        }

        public Criteria andInspectionIsNull() {
            addCriterion("inspection is null");
            return (Criteria) this;
        }

        public Criteria andInspectionIsNotNull() {
            addCriterion("inspection is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionEqualTo(String value) {
            addCriterion("inspection =", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotEqualTo(String value) {
            addCriterion("inspection <>", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionGreaterThan(String value) {
            addCriterion("inspection >", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionGreaterThanOrEqualTo(String value) {
            addCriterion("inspection >=", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionLessThan(String value) {
            addCriterion("inspection <", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionLessThanOrEqualTo(String value) {
            addCriterion("inspection <=", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionLike(String value) {
            addCriterion("inspection like", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotLike(String value) {
            addCriterion("inspection not like", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionIn(List<String> values) {
            addCriterion("inspection in", values, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotIn(List<String> values) {
            addCriterion("inspection not in", values, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionBetween(String value1, String value2) {
            addCriterion("inspection between", value1, value2, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotBetween(String value1, String value2) {
            addCriterion("inspection not between", value1, value2, "inspection");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdIsNull() {
            addCriterion("co_ltd_person_ad is null");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdIsNotNull() {
            addCriterion("co_ltd_person_ad is not null");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdEqualTo(String value) {
            addCriterion("co_ltd_person_ad =", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdNotEqualTo(String value) {
            addCriterion("co_ltd_person_ad <>", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdGreaterThan(String value) {
            addCriterion("co_ltd_person_ad >", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdGreaterThanOrEqualTo(String value) {
            addCriterion("co_ltd_person_ad >=", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdLessThan(String value) {
            addCriterion("co_ltd_person_ad <", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdLessThanOrEqualTo(String value) {
            addCriterion("co_ltd_person_ad <=", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdLike(String value) {
            addCriterion("co_ltd_person_ad like", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdNotLike(String value) {
            addCriterion("co_ltd_person_ad not like", value, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdIn(List<String> values) {
            addCriterion("co_ltd_person_ad in", values, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdNotIn(List<String> values) {
            addCriterion("co_ltd_person_ad not in", values, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdBetween(String value1, String value2) {
            addCriterion("co_ltd_person_ad between", value1, value2, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andCoLtdPersonAdNotBetween(String value1, String value2) {
            addCriterion("co_ltd_person_ad not between", value1, value2, "coLtdPersonAd");
            return (Criteria) this;
        }

        public Criteria andInfoNameIsNull() {
            addCriterion("info_name is null");
            return (Criteria) this;
        }

        public Criteria andInfoNameIsNotNull() {
            addCriterion("info_name is not null");
            return (Criteria) this;
        }

        public Criteria andInfoNameEqualTo(String value) {
            addCriterion("info_name =", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotEqualTo(String value) {
            addCriterion("info_name <>", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameGreaterThan(String value) {
            addCriterion("info_name >", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameGreaterThanOrEqualTo(String value) {
            addCriterion("info_name >=", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLessThan(String value) {
            addCriterion("info_name <", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLessThanOrEqualTo(String value) {
            addCriterion("info_name <=", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLike(String value) {
            addCriterion("info_name like", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotLike(String value) {
            addCriterion("info_name not like", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameIn(List<String> values) {
            addCriterion("info_name in", values, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotIn(List<String> values) {
            addCriterion("info_name not in", values, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameBetween(String value1, String value2) {
            addCriterion("info_name between", value1, value2, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotBetween(String value1, String value2) {
            addCriterion("info_name not between", value1, value2, "infoName");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("id_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("id_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("id_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("id_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("id_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("id_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("id_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("id_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("id_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("id_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("id_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("id_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("id_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("id_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andTransportMachineIsNull() {
            addCriterion("transport_machine is null");
            return (Criteria) this;
        }

        public Criteria andTransportMachineIsNotNull() {
            addCriterion("transport_machine is not null");
            return (Criteria) this;
        }

        public Criteria andTransportMachineEqualTo(String value) {
            addCriterion("transport_machine =", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineNotEqualTo(String value) {
            addCriterion("transport_machine <>", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineGreaterThan(String value) {
            addCriterion("transport_machine >", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineGreaterThanOrEqualTo(String value) {
            addCriterion("transport_machine >=", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineLessThan(String value) {
            addCriterion("transport_machine <", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineLessThanOrEqualTo(String value) {
            addCriterion("transport_machine <=", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineLike(String value) {
            addCriterion("transport_machine like", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineNotLike(String value) {
            addCriterion("transport_machine not like", value, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineIn(List<String> values) {
            addCriterion("transport_machine in", values, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineNotIn(List<String> values) {
            addCriterion("transport_machine not in", values, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineBetween(String value1, String value2) {
            addCriterion("transport_machine between", value1, value2, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportMachineNotBetween(String value1, String value2) {
            addCriterion("transport_machine not between", value1, value2, "transportMachine");
            return (Criteria) this;
        }

        public Criteria andTransportFromIsNull() {
            addCriterion("transport_from is null");
            return (Criteria) this;
        }

        public Criteria andTransportFromIsNotNull() {
            addCriterion("transport_from is not null");
            return (Criteria) this;
        }

        public Criteria andTransportFromEqualTo(String value) {
            addCriterion("transport_from =", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromNotEqualTo(String value) {
            addCriterion("transport_from <>", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromGreaterThan(String value) {
            addCriterion("transport_from >", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromGreaterThanOrEqualTo(String value) {
            addCriterion("transport_from >=", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromLessThan(String value) {
            addCriterion("transport_from <", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromLessThanOrEqualTo(String value) {
            addCriterion("transport_from <=", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromLike(String value) {
            addCriterion("transport_from like", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromNotLike(String value) {
            addCriterion("transport_from not like", value, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromIn(List<String> values) {
            addCriterion("transport_from in", values, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromNotIn(List<String> values) {
            addCriterion("transport_from not in", values, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromBetween(String value1, String value2) {
            addCriterion("transport_from between", value1, value2, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportFromNotBetween(String value1, String value2) {
            addCriterion("transport_from not between", value1, value2, "transportFrom");
            return (Criteria) this;
        }

        public Criteria andTransportByIsNull() {
            addCriterion("transport_by is null");
            return (Criteria) this;
        }

        public Criteria andTransportByIsNotNull() {
            addCriterion("transport_by is not null");
            return (Criteria) this;
        }

        public Criteria andTransportByEqualTo(String value) {
            addCriterion("transport_by =", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByNotEqualTo(String value) {
            addCriterion("transport_by <>", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByGreaterThan(String value) {
            addCriterion("transport_by >", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByGreaterThanOrEqualTo(String value) {
            addCriterion("transport_by >=", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByLessThan(String value) {
            addCriterion("transport_by <", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByLessThanOrEqualTo(String value) {
            addCriterion("transport_by <=", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByLike(String value) {
            addCriterion("transport_by like", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByNotLike(String value) {
            addCriterion("transport_by not like", value, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByIn(List<String> values) {
            addCriterion("transport_by in", values, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByNotIn(List<String> values) {
            addCriterion("transport_by not in", values, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByBetween(String value1, String value2) {
            addCriterion("transport_by between", value1, value2, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportByNotBetween(String value1, String value2) {
            addCriterion("transport_by not between", value1, value2, "transportBy");
            return (Criteria) this;
        }

        public Criteria andTransportToIsNull() {
            addCriterion("transport_to is null");
            return (Criteria) this;
        }

        public Criteria andTransportToIsNotNull() {
            addCriterion("transport_to is not null");
            return (Criteria) this;
        }

        public Criteria andTransportToEqualTo(String value) {
            addCriterion("transport_to =", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToNotEqualTo(String value) {
            addCriterion("transport_to <>", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToGreaterThan(String value) {
            addCriterion("transport_to >", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToGreaterThanOrEqualTo(String value) {
            addCriterion("transport_to >=", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToLessThan(String value) {
            addCriterion("transport_to <", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToLessThanOrEqualTo(String value) {
            addCriterion("transport_to <=", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToLike(String value) {
            addCriterion("transport_to like", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToNotLike(String value) {
            addCriterion("transport_to not like", value, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToIn(List<String> values) {
            addCriterion("transport_to in", values, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToNotIn(List<String> values) {
            addCriterion("transport_to not in", values, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToBetween(String value1, String value2) {
            addCriterion("transport_to between", value1, value2, "transportTo");
            return (Criteria) this;
        }

        public Criteria andTransportToNotBetween(String value1, String value2) {
            addCriterion("transport_to not between", value1, value2, "transportTo");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("startDate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("startDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(String value) {
            addCriterion("startDate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(String value) {
            addCriterion("startDate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(String value) {
            addCriterion("startDate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("startDate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(String value) {
            addCriterion("startDate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(String value) {
            addCriterion("startDate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLike(String value) {
            addCriterion("startDate like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotLike(String value) {
            addCriterion("startDate not like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<String> values) {
            addCriterion("startDate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<String> values) {
            addCriterion("startDate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(String value1, String value2) {
            addCriterion("startDate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(String value1, String value2) {
            addCriterion("startDate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("endDate is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("endDate is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(String value) {
            addCriterion("endDate =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(String value) {
            addCriterion("endDate <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(String value) {
            addCriterion("endDate >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("endDate >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(String value) {
            addCriterion("endDate <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(String value) {
            addCriterion("endDate <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLike(String value) {
            addCriterion("endDate like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotLike(String value) {
            addCriterion("endDate not like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<String> values) {
            addCriterion("endDate in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<String> values) {
            addCriterion("endDate not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(String value1, String value2) {
            addCriterion("endDate between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(String value1, String value2) {
            addCriterion("endDate not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("Date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("Date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("Date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("Date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("Date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("Date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("Date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("Date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("Date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("Date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("Date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("Date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("Date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("Date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pqc_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 05 19:44:14 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pqc_info
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}