package com.azimiao.crud.bean;

public class information {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.id
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.uuid
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.lin
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String lin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.inspection
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String inspection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.co_ltd_person_ad
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String coLtdPersonAd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.info_name
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String infoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.id_number
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.phone_number
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.address
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.source
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.transport_machine
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String transportMachine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.transport_from
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String transportFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.transport_by
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String transportBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.transport_to
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String transportTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.startDate
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.endDate
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.Date
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_info.detail
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.id
     *
     * @return the value of pqc_info.id
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.id
     *
     * @param id the value for pqc_info.id
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.uuid
     *
     * @return the value of pqc_info.uuid
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.uuid
     *
     * @param uuid the value for pqc_info.uuid
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.lin
     *
     * @return the value of pqc_info.lin
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getLin() {
        return lin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.lin
     *
     * @param lin the value for pqc_info.lin
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setLin(String lin) {
        this.lin = lin == null ? null : lin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.inspection
     *
     * @return the value of pqc_info.inspection
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getInspection() {
        return inspection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.inspection
     *
     * @param inspection the value for pqc_info.inspection
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setInspection(String inspection) {
        this.inspection = inspection == null ? null : inspection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.co_ltd_person_ad
     *
     * @return the value of pqc_info.co_ltd_person_ad
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getCoLtdPersonAd() {
        return coLtdPersonAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.co_ltd_person_ad
     *
     * @param coLtdPersonAd the value for pqc_info.co_ltd_person_ad
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setCoLtdPersonAd(String coLtdPersonAd) {
        this.coLtdPersonAd = coLtdPersonAd == null ? null : coLtdPersonAd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.info_name
     *
     * @return the value of pqc_info.info_name
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getInfoName() {
        return infoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.info_name
     *
     * @param infoName the value for pqc_info.info_name
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setInfoName(String infoName) {
        this.infoName = infoName == null ? null : infoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.id_number
     *
     * @return the value of pqc_info.id_number
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.id_number
     *
     * @param idNumber the value for pqc_info.id_number
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.phone_number
     *
     * @return the value of pqc_info.phone_number
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.phone_number
     *
     * @param phoneNumber the value for pqc_info.phone_number
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.address
     *
     * @return the value of pqc_info.address
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.address
     *
     * @param address the value for pqc_info.address
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.source
     *
     * @return the value of pqc_info.source
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.source
     *
     * @param source the value for pqc_info.source
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.transport_machine
     *
     * @return the value of pqc_info.transport_machine
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getTransportMachine() {
        return transportMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.transport_machine
     *
     * @param transportMachine the value for pqc_info.transport_machine
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setTransportMachine(String transportMachine) {
        this.transportMachine = transportMachine == null ? null : transportMachine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.transport_from
     *
     * @return the value of pqc_info.transport_from
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getTransportFrom() {
        return transportFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.transport_from
     *
     * @param transportFrom the value for pqc_info.transport_from
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setTransportFrom(String transportFrom) {
        this.transportFrom = transportFrom == null ? null : transportFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.transport_by
     *
     * @return the value of pqc_info.transport_by
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getTransportBy() {
        return transportBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.transport_by
     *
     * @param transportBy the value for pqc_info.transport_by
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setTransportBy(String transportBy) {
        this.transportBy = transportBy == null ? null : transportBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.transport_to
     *
     * @return the value of pqc_info.transport_to
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getTransportTo() {
        return transportTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.transport_to
     *
     * @param transportTo the value for pqc_info.transport_to
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setTransportTo(String transportTo) {
        this.transportTo = transportTo == null ? null : transportTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.startDate
     *
     * @return the value of pqc_info.startDate
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.startDate
     *
     * @param startdate the value for pqc_info.startDate
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.endDate
     *
     * @return the value of pqc_info.endDate
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.endDate
     *
     * @param enddate the value for pqc_info.endDate
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.Date
     *
     * @return the value of pqc_info.Date
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.Date
     *
     * @param date the value for pqc_info.Date
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_info.detail
     *
     * @return the value of pqc_info.detail
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_info.detail
     *
     * @param detail the value for pqc_info.detail
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}