package com.azimiao.crud.bean;

public class product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.pro_id
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.pro_uuid
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String proUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.plant_name
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String plantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.variety
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String variety;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.specification
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.unit
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.amount
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pqc_product.remark
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.pro_id
     *
     * @return the value of pqc_product.pro_id
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.pro_id
     *
     * @param proId the value for pqc_product.pro_id
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.pro_uuid
     *
     * @return the value of pqc_product.pro_uuid
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getProUuid() {
        return proUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.pro_uuid
     *
     * @param proUuid the value for pqc_product.pro_uuid
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setProUuid(String proUuid) {
        this.proUuid = proUuid == null ? null : proUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.plant_name
     *
     * @return the value of pqc_product.plant_name
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getPlantName() {
        return plantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.plant_name
     *
     * @param plantName the value for pqc_product.plant_name
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setPlantName(String plantName) {
        this.plantName = plantName == null ? null : plantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.variety
     *
     * @return the value of pqc_product.variety
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getVariety() {
        return variety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.variety
     *
     * @param variety the value for pqc_product.variety
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setVariety(String variety) {
        this.variety = variety == null ? null : variety.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.specification
     *
     * @return the value of pqc_product.specification
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.specification
     *
     * @param specification the value for pqc_product.specification
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.unit
     *
     * @return the value of pqc_product.unit
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.unit
     *
     * @param unit the value for pqc_product.unit
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.amount
     *
     * @return the value of pqc_product.amount
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.amount
     *
     * @param amount the value for pqc_product.amount
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pqc_product.remark
     *
     * @return the value of pqc_product.remark
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pqc_product.remark
     *
     * @param remark the value for pqc_product.remark
     *
     * @mbg.generated Sun Nov 05 19:44:14 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}